### ISSUE TITLE
[Website] Add "How to Get Certified" instructions to landing page

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#121]
**Describe the update:**
- update landing page - https://lfnetworking.org/cloud-native-telecom-initiative/ - with "How to Get Certified" instructions 

**Describe why update is needed**
- to have a web property with information on certification
- see former "How to Get Certified" instructions on https://www.cncf.io/training/certification/cnf/

**Content to add:**
How to get certified
**1. Prepare**
Learn about the [certification requirements](https://github.com/lfn-cnti/certification/blob/main/Certified_CNTi_Terms.md) and [technical prerequisites](https://github.com/lfn-cnti/certification/blob/main/instructions.md#prereqs) to prepare your product for certification.

**2. Run the tests**
Follow the [instructions](https://github.com/lfn-cnti/certification/blob/main/instructions.md) to run your tests using the CNF Test Suite. 

**3. Submit**
[Prepare a PR](https://github.com/lfn-cnti/certification/pulls) to submit your results to the CNTi Certification repo on GitHub. Complete the [participation form](https://github.com/lfn-cnti/certification/blob/main/Certified_CNTi_Form.md).

4. Review
A reviewer will approve your PR at which point you are certified.

**Tasks**

- [x] Update draft doc > https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#heading=h.1i5sxjm9swy1
- [x] Draft new landing page content
- [x] Peer review > https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#heading=h.1i5sxjm9swy1
- [x] Share draft with LFN staff and request updates
- [x] QA published changes
- [ ] Close issue

**Comment by Smitholi67** [comment]
@lixuna - LGTM.  One question:  Would it make sense to also consider adding a new link/page for "CNTi Certified CNFs" or should we treat as a seperate update once the GB approves?

**Comment by Smitholi67** [comment]
@lixuna - But we are allowed to add "How to Get Certified" before launching?  I was thinking that both changes could go live at the same time?

**Comment by lixuna** [comment]
We will not have officially certified products before ONE Summit, but we will have the instructions. That is my reasoning for making iterative updates to the landing page.

**Comment by lixuna** [comment]
Adding the information on how to get certified also fulfills a suggestion/question from Jill:
"Will there be any web properties with information on certification? Do you need my help in updating the existing CNTI page?"

**Comment by lixuna** [comment]
@Smitholi67 as a reminder, we have another open issue about displaying Certified CNFs post-launch - [[Web] create a section for Certified CNFs/products on CNTI Landing Page](https://github.com/lfn-cnti/certification/issues/81#top)

**Comment by lixuna** [comment]
April 22, 2024 Update - Lucina sent an email to Jill requesting changes to the landing page -  add "How to Get Certified"

**Comment by lixuna** [comment]
April 22, 2024 Update - ready for peer review

LGTM:

<img width="1264" alt="Screenshot 2024-04-22 at 4 52 23 PM" src="https://github.com/lfn-cnti/certification/assets/11701267/620ba04f-d204-4956-b585-19e6bcf7617d">

**Comment by Smitholi67** [comment]
lgtm
