### ISSUE TITLE
[Documentation] Create Archived folder for CNCF related docs

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#127]
**Describe the update:**
- to archive old documentation that is no longer relevant to CNTi

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Tasks**

- [ ] create an archived folder
- [ ] archive [Certified_CNF_Form.md](https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Form.md)
- [ ]  archive [Certified_CNF_Form.pdf](https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Form.pdf)
- [ ] archive [Certified_CNF_Terms.md](https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Terms.md) 
- [ ] archive [Certified_CNF_Terms.pdf](https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Terms.pdf)
