### ISSUE TITLE
[Design] Create badge for LFN CNTi Certification participants

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#68]
**Describe the update:**
- Create LFN CNTi Certification badge 
- Wording to use on the badge = "CNTi Certified"

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- CNCF Versions of CNF Certified badges are available in https://github.com/cncf/artwork/tree/main/other/cnf-certified

**Tasks**
- [x]  request assistance from design team to create  CNTI Certification badge
- [x] MATRIXX has offered to create the Certification badge and project logo
- [x] brainstorm ideas for the CNTI Certification badge that will be issued to participants who completed the certification process
- [x] Peer review of first draft 
- [ ] Share logo design with Daniel S. for trademark clearance research
- [ ]  use badge in Brand Guide #71

**Comment by lixuna** [comment]
@Smitholi67 we can look at other LFN Projects and how they manage their digital assets for inspiration 

- https://wiki.anuket.io/display/HOME/Digital+Assets

**Comment by lixuna** [comment]
@Smitholi67 the current CNCF CNF Certifcation badge has the wording "Certified CNF" w/ CNCF's logo

Are you suggesting that the new certification program not use the "Certified CNF" wording?
An alternate example of wording: "CNTI Certified"

What we have now:
![cnf-certified-color](https://github.com/lfn-cnti/certification/assets/11701267/8d7557be-8113-4a54-a437-d133ba41df2a)

Drafted possible format of new badge:
![cnti-certified](https://github.com/lfn-cnti/certification/assets/11701267/c4266f64-7cc2-4f0e-8bcb-bbc9f97e0647)

**Comment by Smitholi67** [comment]
@lixuna @taylor - Yes, I think we should be broader than "just" CNFs to allow for future certifications that are related to cloud native networking.  My only concern is that CNTI might become CNTP (P=Project).  Not sure how we address that now or if it can wait until we are a project.  I'm thinking we should avoid a dependency with becoming a project.

**Comment by taylor** [comment]
Go with whatever branding makes the most since now. If it changes later but it is the same cert testing then the companies can use the new badge when it is available

**Comment by lixuna** [comment]
LFN Staff approved open source contributions to this certification badge. MATRIXX design team self-assigned this task to create some options. Thanks!

**Comment by lixuna** [comment]
Yes and I have updated the Terms #70 and Participation #69 forms to reflect "CNTI Certified Marks" to be in alignment with the "CNTI Certified" wording that will be displayed on the new badge design (https://github.com/lfn-cnti/certification/issues/68#issuecomment-1946627099)

For v2.0 CNTI Certification Release, we will have one badge that says "CNTI Certified" to award to Qualified Offerings that pass the CNTI Certification requirements

**Comment by lixuna** [comment]
March 18, 2024 update: 
- MATRIXX Marketing Head granted approval to their design team to create a CNTI logo/badge.

**Comment by lixuna** [comment]
March 20, 2024 update: 
- if we are stylizing the project name to CNTi - with a lowercase i, then the wording displayed on the badge would be "CNTi Certified"

**Comment by lixuna** [comment]
March 27, 2024 update: 
- if this badge will be trademarked, then the badge will need to meet USPTO format requirements. Daniel S. will share those requirements with us

**Comment by lixuna** [comment]
USPTO Image requirements

* Saved as JPG file that does not exceed 5 MB
* Image has a resolution of no less than 300 dots per inch (“DPI”) and no more than 350 DPI
* Image height and width is no less than 250 pixels and no more than 944 pixels (e.g., a valid pixel dimension is 640 x 480 pixels) (NOTE: this isn't a strict requirement, if the design is very long or tall).
* Mark images must not include the trademark, service mark or registration symbols (TM, SM or ®)
* Mark images should be submitted with as little white space around the design as possible
* If color is claimed as part of this mark, the image needs to be in the exact colors as will be used. We will also need to list the colors claimed in the application.
* If color is not claimed as part of this mark, the image needs to be in pure black and white (no grayscale).
* Images created on a Macintosh using Adobe Photoshop or Illustrator must be properly saved with appended file extensions .jpg for use on a Windows system. The USPTO cannot open image files that are not properly saved prior to attachment to the application.
* Adobe Photoshop/Illustrator users must ensure that images are saved with the RGB color scheme. The USPTO cannot accept the CYMK color scheme.
* Do not zip your image files or add any additional compression. JPG files are already compressed.

**Comment by lixuna** [comment]
Other notes: https://docs.google.com/document/d/15GhPSsapi3i2PyNLU6WcB70x_J0-gQCvtfmUs0xhMOo/edit#bookmark=id.jd1lthmneczy

**Comment by Smitholi67** [comment]
Proposal for CNTI Certification badge 

[CNTi Certified Badge_2.pdf](https://github.com/lfn-cnti/certification/files/15337091/CNTi.Certified.Badge_2.pdf)

**Comment by lixuna** [comment]
<img width="655" alt="#68 options - A or B" src="https://github.com/lfn-cnti/certification/assets/11701267/ff21d2b0-ee6f-4633-b1d6-18c78ec4906e">

From the options presented, my vote is for B.

Thank you, @Smitholi67 and MATRIXX team for creating this CNTi Certified Mark!

**Comment by Smitholi67** [comment]
My +1 is for option B.

**Comment by martin-mat** [comment]
(B) +1

**Comment by rich-l** [comment]
(B) +1
