### ISSUE TITLE
[Legal] Participation form to be updated and transferred to LFN ownership

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#69]
**Describe the update:**
Update Certification Participation Form
https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Form.md

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Tasks**

- [x]  draft changes to https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Form.md for LFN CNTI Certification 
- [x]  peer review before sharing with LFN Legal Team
- [x]  request assistance from LFN Legal Team to finalize 
- [x]  upload md to repo > URL will be something like [https://github.com/lfn-cnti/certification/blob/main/Participation_Form.md]
- [x] upload pdf to repo >  URL will be something like [https://github.com/lfn-cnti/certification/blob/main/Participation_Form.pdf]

**Comment by lixuna** [comment]
Draft started at https://docs.google.com/document/d/1iZenH8PfQmjuu8jzoa56ZZX_gdf5WW24mqEbpBbfOKg/edit

**Comment by lixuna** [comment]
@taylor @Smitholi67 Can you please peer review the Participation form draft https://docs.google.com/document/d/1iZenH8PfQmjuu8jzoa56ZZX_gdf5WW24mqEbpBbfOKg/edit?

**Comment by Smitholi67** [comment]
@lixuna - LGTM (no comments or edits)

**Comment by taylor** [comment]
Lgtm

**Comment by lixuna** [comment]
@taylor @Smitholi67 Can you please peer review the Participation form draft https://docs.google.com/document/d/1iZenH8PfQmjuu8jzoa56ZZX_gdf5WW24mqEbpBbfOKg/edit?

I replaced the phase "Certified CNF" with "CNTI Certified"

Per Taylor's concerns, I left the mentions of CNF in the document. However, I'd recommend that we remove it if we are not issuing a "CNF" badge with CNTI.

**Comment by Smitholi67** [comment]
@lixuna @taylor - Same comment as with the Terms and Conditions.  I believe CNTI can offer different badges related to cloud native networking over time.  However, in the short term it is the CNTI Certified CNF that is our first priority.

**Comment by lixuna** [comment]
Tue, Feb 27 - email sent to LFN Staff requesting review

**Comment by lixuna** [comment]
Thur, Feb 29 - LFN Staff submitted a Legal Jira request.

**Comment by lixuna** [comment]
Tue, Mar 5 - updated draft with email address

**Comment by lixuna** [comment]
Mon, Mar 11 - Sent request for ETA to LFN Staff

**Comment by lixuna** [comment]
Wed, Mar 13 - update: Legal Staff is OOO until Mar 14

**Comment by lixuna** [comment]
Wed, Mar 13 - update - LF Legal (Daniel) is out of the office until March 21

**Comment by lixuna** [comment]
Wed, Mar 20 - update - LF Legal (Daniel) is out of the office until March 21

**Comment by lixuna** [comment]
Mon, April 1 - update: Other than updating the relevant URLs when they are available, no changes are required per Chief Brand Counsel review

**Comment by lixuna** [comment]
The CNTi Participation Form .md and .pdf have been uploaded. 

Do we want to move the "Certified CNF" copies into a "Archived" folder?
