### ISSUE TITLE
[Legal] Terms & Conditions form to be updated and transferred to LFN ownership

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#70]
**Describe the update:**
Update Terms & Conditions
https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Terms.md

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Tasks**

- [x]  draft changes to https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Terms.md for LFN CNTI Certification 
- [x] peer review before sharing with LFN Legal Team
- [x]  request assistance from LFN Legal Team to finalize 
- [x]  upload md to repo >  URL will be something like [https://github.com/lfn-cnti/certification/blob/main/CNTI_Certification_Terms.md]
- [x] upload pdf to repo  >  URL will be something like [https://github.com/lfn-cnti/certification/blob/main/CNTI_Certification_Terms.pdf]

**Comment by lixuna** [comment]
Draft started at https://docs.google.com/document/d/1i1oKzyUzJo-rH0EhtZo4XHB3pScgCTXNXs9fuFV6jOE/edit#heading=h.yelbn2vr5xuu

**Comment by lixuna** [comment]
@taylor @Smitholi67 Can you please review the draft https://docs.google.com/document/d/1i1oKzyUzJo-rH0EhtZo4XHB3pScgCTXNXs9fuFV6jOE/edit ?

My main changes to the existing T&C, include:
- replacing CNCF with LFN 
- replacing "CNF Certification" with "CNTI Certification"
- removing cncf specific wording

**Comment by Smitholi67** [comment]
> @taylor @Smitholi67 Can you please review the draft https://docs.google.com/document/d/1i1oKzyUzJo-rH0EhtZo4XHB3pScgCTXNXs9fuFV6jOE/edit ?
> 
> My main changes to the existing T&C, include:
> 
> * replacing CNCF with LFN
> * replacing "CNF Certification" with "CNTI Certification"
> * removing cncf specific wording

@lixuna - Made a few comments in the document, otherwise LGTM.

**Comment by lixuna** [comment]
@taylor @Smitholi67 Can you please review the updated draft https://docs.google.com/document/d/1i1oKzyUzJo-rH0EhtZo4XHB3pScgCTXNXs9fuFV6jOE/edit ?

I replaced the phase "Certified CNF" with "CNTI Certified"

Per Taylor's concerns, I left the mentions of CNF Word Mark in the document. However, I'd recommend that we remove it if we are not issuing a "CNF" badge with CNTI.

**Comment by Smitholi67** [comment]
@lixuna @taylor - I have reviewed now.  It is my view that we will issue "CNF" badges with CNTI.  Over time, there may be other cloud native networking badges that are offered via CNTI.  I think we were mainly looking to ensure that flexibility.

**Comment by lixuna** [comment]
Tue, Feb 27 - email sent to LFN Staff requesting review

**Comment by lixuna** [comment]
Thur, Feb 29 - LFN Staff submitted a Legal Jira request.

**Comment by lixuna** [comment]
Tue, Mar 5 - updated draft with email address

**Comment by lixuna** [comment]
Mon, Mar 11 - Sent request for ETA to LFN Staff

**Comment by lixuna** [comment]
Wed, Mar 13 - update: Legal Staff is OOO until Mar 14

**Comment by lixuna** [comment]
Wed, Mar 20 - Sent request for ETA to LFN Staff and LF Legal

**Comment by lixuna** [comment]
Wed, Mar 20 - update - LF Legal (Daniel) is out of the office until March 21

**Comment by lixuna** [comment]
Tue, Mar 26 - update: meeting schedule with LF Legal tomorrow to review #69 and #70

**Comment by lixuna** [comment]
Mon, April 1 - update: Other than updating the relevant URLs when they are available, no changes are required per Chief Brand Counsel review

**Comment by lixuna** [comment]
The CNTi Terms & Conditions .md and .pdf have been uploaded. 

Do we want to move the "Certified CNF" copies into a "Archived" folder?
