### ISSUE TITLE
[Marketing] update @cnfcert twitter account to reflect CNTI

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#72]
**Describe the update:**
update @cnfcert twitter account to reflect CNTI

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- https://twitter.com/cnfcert
- 

**Tasks**
- [ ] Update name from CNF Certification by # CNCF > tbd
- [ ] Update logo > tbd in #67 
- [ ] Update bio from 📞📱☎️📡🌐Beta release for Cloud native Network Function Certification program - see more at http://cncf.io/cnf > tbd
- [ ] Update website from https://github.com/cncf/cnf-certification > tbd
