### ISSUE TITLE
[Marketing] Create marketing toolkit for CNTI Certification launch

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#73]
**Describe the update:**
Create marketing toolkit for CNTI Certification launch

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Tasks**
- [x] Create google doc for CNTI Marketing Toolkit 
- [x] Draft Social media sample posts
- [ ] Share with participants and supporters to help promote the CNTI Certification

**Comment by lixuna** [comment]
Draft started at https://docs.google.com/document/d/1A9klSs_ED9GTyG9wZEVxHJjkv4peDdAhOOI3Jper8V4/edit

Contents will include: 

- Social media sample posts
   - 1-2 tweets/X
   - 1 Linkedin post
   
- Email / website blurb

**Comment by lixuna** [comment]
social media examples are ready for peer review

**Comment by Smitholi67** [comment]
@lixuna - Can you confirm that the social media posts are voluntarily done by participating companies after launch of the Certification program?

**Comment by lixuna** [comment]
yes

**Comment by lixuna** [comment]
* End users, contributors, participants of CNTi are encouraged to share their support on social media. The sample posts that can be used as-is or as inspiration.
