### ISSUE TITLE
[Documentation] update instructions.md for self-certification participants (v2.0.0-beta)

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#74]
**Describe the update:**
update instructions for self-certification participants

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- what we have now: https://github.com/lfn-cnti/certification/blob/main/instructions.md

**Tasks**
- [x] Draft new instructions based on new CNTI Certification process
- [x] update section called The Tests
- [x] update section called Prereqs
- [x] update section called Running
- [x] update section called Uploading
- [x] Update email address in section called Review - If you don't see a response within 5 business days, please send an email to [lfn-cnti@lfnetworking.org](mailto:lfn-cnti@lfnetworking.org).
- [x] Update email address in section called Issues - Questions and comments can also be sent via email to [lfn-cnti@lfnetworking.org](mailto:lfn-cnti@lfnetworking.org).

**Comment by lixuna** [comment]
PR submitted - [Update instructions.md](https://github.com/lfn-cnti/certification/pull/110#top)
- Changed CNTI to CNTi (lowercase i)
- Updated "57 tests" URL From v1.0-beta to v2.0-beta
- Updated "certification binary release" link to upcoming https://github.com/cnti-testcatalog/testsuite/releases/tag/v1.0.0

To do:
- tally total number of tests and update "There are ## tests included in the CNTi Certification v2.0-beta."

**Comment by lixuna** [comment]
Blocked: 
- Help Wanted - tally total number of tests and update "There are ## tests included in the CNTi Certification v2.0-beta."

**Comment by lixuna** [comment]
Blocked:

Help Wanted - tally total number of tests and update "There are ## tests included in the CNTi Certification v2.0-beta."

**Comment by lixuna** [comment]
New cnti-testcatalog version for CNTi Certification has been released - https://github.com/cnti-testcatalog/testsuite/releases/tag/v1.2.0
