### ISSUE TITLE
[Documentation] Create "Certification List of Tests" for CNTI Certification v2.0-beta

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#78]
**Describe the update:**
Create "Certification List of Tests" for CNTI Certification v2.0-beta

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- what we have now: https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md
- what we want to have: an updated file saved as "https://github.com/lfn-cnti/certification/blob/main/docs/CNTICertification-2.0-beta.md"

**Tasks**
- [x] Draft new list of tests based on the updated [V2.0 CNTI](https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit) Certification Tests
- [x] save to https://github.com/lfn-cnti/certification/blob/main/docs/CNTICertification-2.0-beta.md
- [x] to do: update Total number of tests in cnf-testsuite
- [x] to do: update number of Normal Tests
- [x] to do: update number of Bonus Tests
- [x] to do: update all URLs to point to v1.0.0 cnti-testsuite release (BLOCKED: v1.0.0 to be released, URL TBD: https://github.com/cnti-testcatalog/testsuite/releases/tag/v1.0.0)
- [ ] to do: update all docs to explain what the test does
- [ ] to do: update all tests with Test ID/command name
- [ ] Peer Review

**Comment by lixuna** [comment]
CNTI V2.0 List of Essential Tests was reviewed in the CNTI Certification call on Thursday, March 14, 2024 at 9am PT

Community Approval for [V2.0 CNTI](https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit) Certification Tests was granted.

We can move forward with publishing the list of tests for v2.0.

**Comment by lixuna** [comment]
Request to contributors: 

-  comment or create PR with "Total number of tests in cnf-testsuite"
- comment or create PR with "number of Normal Tests"
- comment or create PR with "number of Bonus Tests"
