### ISSUE TITLE
[Web] create a section on https://landscape.lfnetworking.org/ for Certified CNFs/products

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#80]
**Describe the update:**
create a section on https://landscape.lfnetworking.org/ for Certified CNFs/products

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- what we have now: "Certified CNFs" on https://landscape.cncf.io/?group=certified-partners-and-providers&view-mode=grid

**Tasks**
- [ ] Decide if we want to showcase certified products on the https://landscape.lfnetworking.org/
- [ ] Mock design ideas
- [ ] Request LFN web team to implement changes
- [ ] tbd
