### ISSUE TITLE
[Web] create a section for Certified CNFs/products on CNTI Landing Page

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#81]
**Describe the update:**
create a section on for Certified CNFs/products on landing page

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- what we have now: https://www.cncf.io/training/certification/cnf/#logos
- https://lfnetworking.org/cloud-native-telecom-initiative/

**Tasks**
- [ ] Decide if we want to showcase certified products on the Landing Page https://lfnetworking.org/cloud-native-telecom-initiative/
- [ ] Mock design ideas
- [ ] Request LFN web team to implement changes
- [ ] tbd
