### ISSUE TITLE
[Research] Select tests that will be included in v2.0 GA launch of CNTI Certification

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#82]
**Describe the update:**
Select tests that will be included in v2.0 GA launch of CNTI Certification

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- what we have now:  https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md

**Tasks**
- [x] Review existing tests in 'cert' command #79 
- [x] Add new tests from https://github.com/cnti-testcatalog/testsuite/blob/main/USAGE.md
- [x] Add Anuket tests as defined in [[Research] Identify existing tests in CNTI Test Catalog that are in alignment with Anuket Test Case Traceability to RA2 Requirements](https://github.com/cnti-testcatalog/testcatalog/issues/3#top)
- [ ] Add Nephio tests (if available) 
- [ ] Add Sylva tests (if available) 
- [x] Add/modify certification tests, per #79 and #87 
- [x] Propose v2.0 tests for certification
- [x] Peer Review 
- [ ] Request changes from cnti-testcatalog team to update 'cert' command to modify tests for v2.0 GA launch
- [ ] tbd

**Additional Context:**
- This issue blocks #78

**Comment by lixuna** [comment]
See also #87

**Comment by Smitholi67** [comment]
@lixuna @taylor  - Please review the proposed list of V2.0 Essential Tests outlined here:  [https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit?usp=sharing]

**Comment by lixuna** [comment]
Reviewed and added suggested edits

**Comment by lixuna** [comment]
CNTI V2.0 List of Essential Tests was reviewed in the CNTI Certification call on Thursday, March 14, 2024 at 9am PT

Community Approval for [V2.0 CNTI](https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit) Certification Tests was granted.

We will move forward with requesting code changes in the cnf-testsuite framework
