### ISSUE TITLE
[Admin] Create an email address for CNTI Certification program

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#84]
**Describe the update:**
Create an email address for CNTI Certification participants to submit their signed Participation Form

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- The CNCF version of CNF Certification used cnfcertification@cncf.io

**How will this email address be used?**
- End users will send their signed Participation Form to the email address
- Reviewers/Certification Maintainers will make sure the Participation Form meets the "Policy Requirements" in the [Reviewing Guidelines](https://github.com/lfn-cnti/certification/blob/main/reviewing.md)

**Tasks**

- [x] Propose an email address name + Group for CNTI Certification
- [x] Peer review of proposal
- [x] Request LFN Staff help in creating the email address group 
- [x] Add email address to [Terms & Conditions](https://docs.google.com/document/d/1i1oKzyUzJo-rH0EhtZo4XHB3pScgCTXNXs9fuFV6jOE/edit)
- [x] Add email address to [Participation form](https://docs.google.com/document/d/1iZenH8PfQmjuu8jzoa56ZZX_gdf5WW24mqEbpBbfOKg/edit#heading=h.363vnu9lfzcu)
- [x] Peer review

**Comment by lixuna** [comment]
Proposing the email address name: 
- lfn-cnti@linuxfoundation.org

Proposing the email group members: 
- Jill Lovato <jlovato@linuxfoundation.org>
- Sandra Jackson <sjackson@linuxfoundation.org>
- Ranny Haiby <rhaiby@linuxfoundation.org>,
- Kenny Paul <kpaul@linuxfoundation.org>
- Olivier Smith <olivier.smith@matrixx.com>,
- Taylor Carpenter <taylor@vulk.coop>,
- Lucina Stricko <lucina@vulk.coop>

**Comment by lixuna** [comment]
@Smitholi67 @taylor Please review the above proposal and comment if any changes are needed

**Comment by taylor** [comment]
Lgtm
lfn-cnti similar to other lfn lists

**Comment by Smitholi67** [comment]
Lgtm

**Comment by lixuna** [comment]
Tue, Feb 27 - no response to email sent on Feb 21. I resent and added C.Cain to thread.

**Comment by lixuna** [comment]
Mon, Mar 4 - no response. "3rd request - Email address for CNTI Certification program" sent.

**Comment by lixuna** [comment]
Mon, Mar 4 - update - email address will be [lfn-cnti@lfnetworking.org](mailto:lfn-cnti@lfnetworking.org)

**Comment by lixuna** [comment]
lfn-cnti@lfnetworking.org has been created

Test email sent. Subject: "Initial Test Email for LFN-CNTI Admin Forward <EOM>"

Test email received:
- [x] @lixuna 
- [ ] @taylor 
- [ ] @Smitholi67

**Comment by taylor** [comment]
got it
