### ISSUE TITLE
[Website] Add FAQ section to landing page

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#96]
**Describe the update:**
- update landing page - https://lfnetworking.org/cloud-native-telecom-initiative/ - with frequently asked questions

**Describe why update is needed**
- address misunderstandings about CNTi

CNTi Certification:

- is self executable via self-certification instructions
- is focused on core cloud-nativeness
- Is vendor-neutral
- Results are reviewed by the community
- Results provide remediation on failed tests to help developers improve the cloud-nativeness of the product
- Offers a one year expiration on tested product version
- Offers a “CNTi Certified” Badge to display with your Certified Product
- TBD

**Tasks**

- [x] Update draft doc > https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#heading=h.1i5sxjm9swy1
- [x] Draft new landing page content
- [x] Share draft with LFN staff and request updates
- [x] QA published changes
- [ ] Close issue

**Comment by lixuna** [comment]
WIP - Draft started in https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#bookmark=id.ty12fzvfhujs

**Comment by Smitholi67** [comment]
@lixuna @taylor - Just an idea, we might do something simple like this:  
![image](https://github.com/lfn-cnti/certification/assets/61708516/0a8e2348-ed4e-473a-b81a-b9a4f950ca57)

**Comment by lixuna** [comment]
Another option would be to extend the content within the 3 existing light blue boxes. 

### What we have now:

Best Practices
Developing cloud native and Kubernetes-native best practices for networking.

Test Catalog
Creation of a robust testing framework and infrastructure, including functional, non-functional, and end-to-end tests.

Cloud Native Certification
Building on the foundations of LFN and CNCF certification programs and extending to address the needs of modern Cloud Native Network Functions. 

---

### What we would like to see:

Best Practices
Documents cloud native and Kubernetes-native best practices for networking.
Recommends vendor-neutral, foundational. 
Collaborates with LF Networking projects.

Test Catalog
Creates a robust testing framework and infrastructure.
Develops functional, non-functional, and end-to-end tests.
Provides remediation on failed tests to help application developers.

Cloud Native Certification
Built on the foundation of CNCF’s CNF Certification program.
Extended to address the needs of modern Cloud Native Network Functions.
Self executable via self-certification instructions and community-reviewed.

---

Also added to https://docs.google.com/document/d/1lF3rR3z39B0troqducYxd0vMT8WE9hvFWC3OCphc760/edit#bookmark=id.ty12fzvfhujs

**Comment by Smitholi67** [comment]
@lixuna - I think the proposed changes look good.  My only comment is that "works with LF Networking Projects" is true for both best practices and test catalog.

**Comment by lixuna** [comment]
@Smitholi67 please review these updates: I added "based on best practices" to the test catalog

Best Practices
Documents cloud native and Kubernetes-native best practices for networking.
Recommends vendor-neutral, foundational best practices. 
Collaborates with LF Networking projects.

Test Catalog
Develops functional, non-functional, and end-to-end tests based on best practices.
Creates a robust testing framework and infrastructure.
Provides remediation on failed tests to help application developers.

Certification
Built on the foundation of CNCF’s CNF Certification program.
Extended to address the needs of modern Cloud Native Network Functions.
Self-executable and community-reviewed.

**Comment by Smitholi67** [comment]
@lixuna - Looks good!

**Comment by lixuna** [comment]
April 22, 2024 Update - Lucina sent an email to Jill requesting changes to the landing page -  Update light blue boxes with additional content for Best Practices, Test Catalog, Certification

**Comment by lixuna** [comment]
April 22, 2024 Update - ready for peer review https://lfnetworking.org/cloud-native-telecom-initiative/

LGTM:

<img width="1300" alt="Screenshot 2024-04-22 at 4 51 39 PM" src="https://github.com/lfn-cnti/certification/assets/11701267/6e748beb-e064-4a12-8fba-5e2412d759f2">

**Comment by Smitholi67** [comment]
lgtm
